Name : Sanjeev Kumar Khatri

Roll no : 23

Group : CS

Assignment : 07

Githublink : https://github.com/darkamgel/machinelearning-LAB

Practical Assignment - 7

1. Reinforcement Learning 
2. Creating an environment 
3. Building a learning agent 
4. Example code for q-learning



## Reinforcement Learning 
Reinforcement learning is the training of machine learning models to make a sequence of decisions. The agent learns to achieve a goal in an uncertain, potentially complex environment. In reinforcement learning, an artificial intelligence faces a game-like situation. The computer employs trial and error to come up with a solution to the problem. To get the machine to do what the programmer wants, the artificial intelligence gets either rewards or penalties for the actions it performs. Its goal is to maximize the total reward.

### Creating required environment

In [ ]:
pip install gym

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [6]:
import argparse
import gym

# Define a function to parse the input arguments. We will be able to specify the type of environment we want to run,

def build_arg_parser():
    parser = argparse.ArgumentParser(description='Run an environment')
    parser.add_argument('--input-env', dest='input_env', required=True,
            choices=['cartpole', 'mountaincar', 'pendulum', 'taxi', 'lake'], 
            help='Specify the name of the environment')
    return parser

# Define the main function and parse the input arguments,

def run(input_env):
    name_map = {'cartpole': 'CartPole-v1', 
                'mountaincar': 'MountainCar-v0',
                'pendulum': 'Pendulum-v0',
                'taxi': 'Taxi-v1',
                'lake': 'FrozenLake-v0'}

# Create a mapping from input argument string to the names of the environments as specified in the OpenAI Gym package,
 # Create the environment and reset it

    env = gym.make(name_map[input_env])
    env.reset()


# Iterate 1000 times and take action during each step:
    for _ in range(1000):
      
        env.render()

        env.step(env.action_space.sample()) 

In [ ]:
pip install pygame

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 21.8 MB 1.4 MB/s 


In [8]:

import os
os.environ['SDL_VIDEODRIVER']='dummy'
import pygame
pygame.display.set_mode((640,480))
run("cartpole")

/usr/local/lib/python3.7/dist-packages/gym/envs/classic_control/cartpole.py:180: UserWarning: WARN: You are calling 'step()' even though this environment has already returned terminated = True. You should always call 'reset()' once you receive 'terminated = True' -- any further steps are undefined behavior.
  "You are calling 'step()' even though this "


In [9]:
run("mountaincar")

### Building a learning agent

Now, Let's see how we can  build a learning agent that can achieve a goal. The learning agent will learn how to achieve a goal.

In [13]:

# Define a function to parse the input arguments:

def build_arg_parser():
    parser = argparse.ArgumentParser(description='Run an environment')
    parser.add_argument('--input-env', dest='input_env', required=True,
            choices=['cartpole', 'mountaincar', 'pendulum'], 
            help='Specify the name of the environment')
    return parser

# Parse the input arguments:

def run(input_env):

    name_map = {'cartpole': 'CartPole-v1', 
                'mountaincar': 'MountainCar-v0',
                'pendulum': 'Pendulum-v0'}

    env = gym.make(name_map[input_env])
 
    for _ in range(20):
        observation = env.reset()

        for i in range(100):
            env.render()

            print(observation)
 
            action = env.action_space.sample()
            observation, reward, done, info = env.step(action)
            if done:
                print('Episode finished after {} timesteps'.format(i+1))
                break

In [14]:
run("cartpole")

[-0.00453215  0.01945068  0.03870164  0.01936232]
[-0.00414314 -0.17620431  0.03908889  0.32400048]
[-0.00766723  0.01833988  0.0455689   0.04389631]
[-0.00730043  0.21277978  0.04644682 -0.23406814]
[-0.00304483  0.01702603  0.04176546  0.07289626]
[-0.00270431 -0.17866902  0.04322338  0.37845835]
[-0.00627769 -0.3743773   0.05079255  0.6844503 ]
[-0.01376524 -0.57016635  0.06448156  0.9926817 ]
[-0.02516857 -0.766089    0.08433519  1.3048993 ]
[-0.04049035 -0.962173    0.11043318  1.6227452 ]
[-0.0597338  -1.1584083   0.14288808  1.9477065 ]
[-0.08290197 -0.9650676   0.18184221  1.7025173 ]
Episode finished after 12 timesteps
[-0.03924851  0.01522807  0.02386472 -0.01802256]
[-0.03894395 -0.18022786  0.02350427  0.2820934 ]
[-0.0425485   0.01455108  0.02914614 -0.00308468]
[-0.04225748 -0.18097648  0.02908444  0.29864985]
[-0.04587701  0.01371908  0.03505744  0.01527964]
[-0.04560263 -0.18188764  0.03536303  0.31881422]
[-0.04924038  0.01271328  0.04173932  0.0374899 ]
[-0.04898612 -

### Example code for q-learning

In [15]:
import numpy as np
from random import randint
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection

# defines the reward/link connection graph
R = np.matrix([[-1, -1, -1, -1,  0,  -1],
              [-1, -1, -1,  0, -1, 100],
              [-1, -1, -1,  0, -1,  -1],
              [-1,  0,  0, -1,  0,  -1],
              [ 0, -1, -1,  0, -1, 100],
              [-1,  0, -1, -1,  0, 100]])
Q = np.zeros_like(R)

The -1’s in the table means there isn’t a link between nodes. For example, State ‘a’ cannot go to State ‘b’.

In [16]:
# learning parameter
gamma = 0.8

# Initialize random_state
initial_state = randint(0,4)


# This function returns all available actions in the state given as an argument
def available_actions(state):
    current_state_row = R[state,]
    av_act = np.where(current_state_row >= 0)[1]
    return av_act

# This function chooses at random which action to be performed within the range of all the available actions.
def sample_next_action(available_actions_range):
    next_action = int(np.random.choice(available_act,1))
    return next_action

# This function updates the Q matrix according to the path selected and the Q learning algorithm
def update(current_state, action, gamma):
    
    max_index = np.where(Q[action,] == np.max(Q[action,]))[1]

    if max_index.shape[0] > 1:
        max_index = int(np.random.choice(max_index, size = 1))
    else:
        max_index = int(max_index)
    max_value = Q[action, max_index]

    Q[current_state, action] = R[current_state, action] + gamma * max_value    

# Get available actions in the current state
available_act = available_actions(initial_state) 

# Sample next action to be performed
action = sample_next_action(available_act) 

In [18]:
#let's Train over 100 iterations, re-iterate the process above).
for i in range(100):
    current_state = np.random.randint(0, int(Q.shape[0]))
    available_act = available_actions(current_state)
    action = sample_next_action(available_act)
    update(current_state,action,gamma)
# Normalize the "trained" Q matrix
print ("Trained Q matrix: \n", Q/np.max(Q)*100)

Trained Q matrix: 
 [[  0.           0.           0.           0.          75.65789474
    0.        ]
 [  0.           0.           0.          60.52631579   0.
  100.        ]
 [  0.           0.           0.          63.81578947   0.
    0.        ]
 [  0.          79.8245614   48.24561404   0.          75.65789474
    0.        ]
 [ 60.52631579   0.           0.          63.81578947   0.
  100.        ]
 [  0.          79.8245614    0.           0.          79.8245614
  100.        ]]


In [19]:
# Testing
current_state = 2
steps = [current_state]

while current_state != 5:
    next_step_index = np.where(Q[current_state,] == np.max(Q[current_state,]))[1]
    if next_step_index.shape[0] > 1:
        next_step_index = int(np.random.choice(next_step_index, size = 1))
    else:
        next_step_index = int(next_step_index)
    steps.append(next_step_index)
    current_state = next_step_index

print ("Best sequence path: ", steps)

Best sequence path:  [2, 3, 1, 5]
